// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSHBVUtSldB2wBGAHHWuKXrSF1ENGgOSs',
    appId: '1:1031936834226:web:52a0689128b7dff6d067ab',
    messagingSenderId: '1031936834226',
    projectId: 'vision11demo',
    authDomain: 'vision11demo.firebaseapp.com',
    storageBucket: 'vision11demo.appspot.com',
    measurementId: 'G-QHEMLDKJNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpatCxVX9qJ7ysIl5U1oitqX6bo8T7toQ',
    appId: '1:1031936834226:android:d3a610aeafeda427d067ab',
    messagingSenderId: '1031936834226',
    projectId: 'vision11demo',
    storageBucket: 'vision11demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy0aDzIpgvSSV8DX-m0YLemws3tE53muc',
    appId: '1:1031936834226:ios:15e9c68dbd2aa809d067ab',
    messagingSenderId: '1031936834226',
    projectId: 'vision11demo',
    storageBucket: 'vision11demo.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy0aDzIpgvSSV8DX-m0YLemws3tE53muc',
    appId: '1:1031936834226:ios:98836cacb20e5e3ad067ab',
    messagingSenderId: '1031936834226',
    projectId: 'vision11demo',
    storageBucket: 'vision11demo.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
